version: "3.8"

services:
  backup_proxy:
    build:
      context: .
    image: makeshift27015/nginx-retry-proxy:latest

  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"

  nginx_upstream:
    image: nginx
