version: "3.8"

services:
  backup_proxy:
    build:
      context: .
    image: makeshift27015/nginx-retry-proxy:latest
    environment:
      - PORT=8081
      - HEALTHCHECK_PATH=/health
      - RESPONSE_HTTP_CODE=301
      - RESPONSE_HTTP_HEADERS="Location:http://example.com, Cache-Control :no-cache"
      - HEALTHCHECK_REPLIES=3

  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"

  nginx_upstream:
    image: nginx
